[workspace]
resolver = "2"
members = [".", "shai-macros", "shai-llm", "shai-core", "shai-cli"]

[patch.crates-io]
ratatui = { git = "https://github.com/Marlinski/ratatui", branch = "feature/viewport-resize-v29" }